import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Layout from "@/components/Layout";
import Header from "@/components/Header";
import Contents from "@/components/Contents";
import Footer from "@/components/Footer";
import { TOKEN, DATABASE_ID } from "../../config";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ projectNames }: { projectNames: string[] }) {
  console.log(projectNames);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Header>SEJIN OH</Header>
        <Contents projectNames={projectNames} />
        <Footer />
      </Layout>
    </>
  );
}

export async function getStaticProps() {
  const options = {
    method: "POST",
    headers: {
      accept: "application/json",
      "Notion-Version": "2022-06-28",
      "content-type": "application/json",
      Authorization: `Bearer ${TOKEN}`,
    },
    body: JSON.stringify({ page_size: 100 }),
  };

  const res = await fetch(
    `https://api.notion.com/v1/databases/${DATABASE_ID}/query`,
    options
  );

  const projects = await res.json();

  const projectNames = projects.results.map(
    (aProject: { properties: any; id: any }) =>
      aProject.properties.Name.title[0].plain_text
  );

  console.log(`projectNames: ${projectNames}`);

  return {
    props: {
      projectNames,
    }, // will be passed to the page component as props
  };
}
